### ISSUE TITLE
Examples, docs, best practices

### ISSUE THREAD

**Issue by ReblochonMasque** [glyph/automat#100]
I am working my may through the docs to discover and learn automat. I am finding the docs well done, and the library well documented. It seems, however, to mostly cater to the _"already well informed gentleman"_'s questions though!  
What I think is missing, is a sort of a step by step process for creating a state machine, and using it.

I am willing to contribute and write such a process, but I am afraid I need a little bit of feedback, for calibration, and best practices:

I have written a state machine that models the [scoring of a tennis game](https://gist.github.com/ReblochonMasque/0ff302bc48b78e7938a939d2c12ff824), linked as a `gist`. If someone would provide feedback, and maybe guidance, I would spend the time to polish it, and attempt to produce a useful step by step tutorial to include in the documentation of the library.

A short list of what I think are bad ideas I used to solve the problems encountered:
- use of `from automat._core import NoTransition` to use in a try/except block to exit a loop in the client. The problem was: how can I know the process has ended (reach a winning state).
- Creating a "pre-initial state" (instead of starting at `_love_love`) that requires a state transition to the real initial state in order to allow for variable initialization - maybe there is a better way to init variables? or maybe there is an approach that does not require these variables?:
```python
    @_machine.state(initial=True)
    def _state__(self):
        """
        State __
        """

    @_machine.output()
    def _output_on_initialize_game(self):
        """
        State __ -> State love-love
        """
        self._server_points = 0
        self._receiver_points = 0
        self.winner = None
        self._set_increments()
        self._show_score()
```

- having to build a list of states to assign a query to each:
```python
    states = (_love_love, _15_love, _love_15, _love_30, _love_40, _30_love, _40_love, _15_all, _30_15, _15_30
              , _40_15, _30_all, _15_40, _30_40, _40_30, _40_all, _deuce, _advantage_serve, _advantage_receive,
              _server_wins, _receiver_wins)

    for state in states:
        state.upon(query_score, enter=state, outputs=[_output_on_query_score], collector=itemgetter(0))
```
--> maybe there is an `automat.method` that does this.
--> or maybe there is a better approach.
--> attaching a these queries as a state transition from/to the same state is also making the rendering of the [Tennis Game state machine visualization](http://s994.photobucket.com/user/FredInChina/media/tennis.tennisgamescore.TennisGame._machine.dot_zps0m9bdssf.png.html) overly crowded by adding a transition to self to each state..
- Having to initiate class constants in order to mimic the passing of parameters that I could not quite figure out. It seemed to be a way to prevent a multiplication of `machine.input / machine.output` pairs to handle the transitions each time a player scored. 
```python
    SCORING = {0: 15, 15: 15, 30: 10}
    SCORING.update({k: 1 for k in range(40, 80)})
```

**Comment by ReblochonMasque** [comment]
bump

**Comment by glyph** [comment]
This is potentially a great example! But I don't understand what specific questions you're asking, aside from "maybe there's a better approach".  Maybe there is!  But I definitely don't have time to dive into your example in depth and meditate on every aspect of it.

I'm going to close this because it's really just a bunch of questions and not an actionable issue with the library; however, I very much hope you can break this up into smaller, more direct questions, and perhaps write up several smaller issues that more clearly illustrate the concrete problems you're having.
