### ISSUE TITLE
f strings raise syntax error in visualize

### ISSUE THREAD

**Issue by ReblochonMasque** [glyph/automat#101]
f strings in automat class or client raise a `SyntaxError` in visualize.  
Maybe it is a `GraphViz` problem?

download and save [this gist](https://gist.github.com/ReblochonMasque/0ff302bc48b78e7938a939d2c12ff824) as `tennisgamescore.py` in a tree structure like this:
```
tennis/
├── __init__.py
└── tennisgamescore.py
```
uncomment line 23 and run `automat-visualize tennis` to reproduce.

**Comment by ReblochonMasque** [comment]
this did not attract much interest...

**Comment by glyph** [comment]
The visualizer doesn't parse modules, it just imports them. The problem here is that you were using the wrong version of Python (3.5 or earlier.)
