### ISSUE TITLE
attrs 19.2.0 cmp deprecation warnings

### ISSUE THREAD

**Issue by twm** [glyph/automat#117]
automat (as used in Twisted) is producing deprecation warnings since the [attrs 19.2.0](http://www.attrs.org/en/stable/changelog.html#id1) release last week:

```
automat/_methodical.py:209: DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead.
automat/_methodical.py:288: DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead.
```

This is Automat 0.7.0.

**Comment by hynek** [comment]
I can offer a PR.  Would you like to bump the dep to 19.2 like hypothesis or do you want a [hybrid approach like pytest](https://github.com/pytest-dev/pytest/pull/5902/files)?

**Comment by twm** [comment]
IMO bumping the dep is fine &mdash; that's what we did for Twisted.
