### ISSUE TITLE
release next version (22.x.x)

### ISSUE THREAD

**Issue by moshez** [glyph/automat#139]

**Comment by DMRobertson** [comment]
Hi, do you have a rough idea of when the next release is planned for? We'd love to be able to use one which includes a fix to https://github.com/glyph/automat/issues/135 for Python 3.11 compatibility. (Cross-reference: https://github.com/matrix-org/synapse/pull/13812#issuecomment-1247083641)

**Comment by DMRobertson** [comment]
https://pypi.org/project/Automat/22.10.0/ was released, corresponding to https://github.com/glyph/automat/releases/tag/v22.10.0. Many thanks!

**Comment by glyph** [comment]
OK I guess this was fixed in 2022 :)
