### ISSUE TITLE
Deploy updated docs 

### ISSUE THREAD

**Issue by Murtagy** [glyph/automat#154]
The docs are correct in source, but incorrect on web
![image](https://github.com/glyph/automat/assets/36745768/f179032d-e5bc-4bd8-b8b0-d2003d1efebd)
![image](https://github.com/glyph/automat/assets/36745768/e08827f2-d446-4c85-88b2-ee249abdac6f)

**Comment by glyph** [comment]
I think that the readthedocs configuration should be fixed now, and current versions are being built and deployed.
