### ISSUE TITLE
Make self-loops easier

### ISSUE THREAD

**Issue by markrwilliams** [glyph/automat#17]
Per @moshez's suggestion and @glyph's API design guidance:

Writing a transition that loops back to a given state should be as easy as omitting `enter`.

So this:

``` python
someState.upon(someInput, enter=someState, ....)
```

should instead be:

``` python
someState.upon(someInput, ....)
```

One suggestion: what if this were a new method, instead?  Like so:

``` python
someState.loopOn(someInput, ...)
```

I think that reads a little nicer, and keeps `enter` a required argument for `upon`, which, in general, _should_ require a state to enter.

**Comment by glyph** [comment]
I would rather just have `upon`.

In english:

"In the `someState` state, upon the `someInput` input, output `someOutput`."

"In the `someState` state, upon the `someInput` input, output `someOutput` and enter the `other` state."

It seems OK to just omit "enter" on that one method.

**Comment by markrwilliams** [comment]
I didn't create an issue for this, but I recall discussing making `outputs` optional.  If we don't do that, then I'm also OK with just omitting enter; but if we do, `someState.upon(someInput)` seems too terse.

**Comment by glyph** [comment]
`outputs` is currently mandatory: https://github.com/glyph/automat/blob/master/automat/_methodical.py#L35

I ''think'' I'm OK with `someState.upon(someInput)`.  That does fail the how-would-I-say-it-in-English test, but it's logically consistent, and there's nothing wrong with creating a no-output self-loop...

**Comment by warner** [comment]
You could use `someState.upon(someInput, ignore=True)` if you want to make it more obvious that omitting both `enter=` and `outputs=` means to do nothing. Or spell it `do="nothing"` if you really want to make it sound like English.
