### ISSUE TITLE
Not all outputs get run if the collector does not exhaust the generator.

### ISSUE THREAD

**Issue by tomprince** [glyph/automat#30]
If I have multiple outputs, and want to return the result of the first one, an obvious option is to 
```python
state.upon(input, enter=next_state, outputs=[first_output, second_output], collect=next)
```
But since collect is passed a generator of outputs, the collector being `next` causes the second output to not be evaluated.

This is related to #18.

**Comment by glyph** [comment]
@warner — @exarkun asked if this was actually closed.  Do you recall if #56 actually did fix this in the general sense?

**Comment by markrwilliams** [comment]
@glyph #56 did fix this in general [by creating a temporary list inside `doInput`](https://github.com/glyph/automat/pull/56/files#diff-e461f68b2bb2507e44225923c3f13ccaL128).

**Comment by markrwilliams** [comment]
Note that this means `collector=next` doesn't work any more, because `list`s are not themselves iterators.  This was a backwards incompatible change but nobody noticed or has complained, so :relieved:
