### ISSUE TITLE
command-line tool for actually doing visualization

### ISSUE THREAD

**Issue by glyph** [glyph/automat#5]
There's some code now that can do state-machine visualization, but actually getting a PNG out should be as simplified as possible.

**Comment by markrwilliams** [comment]
Would you be opposed to using a separate library to generate the dot output?
[graphviz](https://github.com/xflr6/graphviz) (*not* python-graphviz, or pygraphviz) works with Python 2 and 3, does not require any compilation, and uses the MIT license.

**Comment by glyph** [comment]
Not at all! That strikes me as a totally separate issue though.

**Comment by markrwilliams** [comment]
Sorry for the lack of context -- I asked because I'm toying with an approach to this issue that would benefit from the graphviz library, and wanted to be sure it wouldn't be immediately useless because of that dependency.

**Comment by glyph** [comment]
Nope! By all means, proceed. It would be great if somebody else did this for me :)

**Comment by glyph** [comment]
Fixed by #21
