### ISSUE TITLE
bodies of Inputs are executed, but shouldn't be

### ISSUE THREAD

**Issue by warner** [glyph/automat#50]
With Automat-0.5.0, the following program:

```python
from automat import MethodicalMachine
class Code(object):
    m = MethodicalMachine()
    @m.state(initial=True)
    def S0(self):
        print "S0"
    @m.state()
    def S1(self):
        print "S1"

    @m.input()
    def go(self):
        print "go"
    S0.upon(go, enter=S1, outputs=[])

print "doing construction"
c = Code()
print "doing go"
c.go()
print "done"
```

produces the following output:

```% python input-run.py
doing construction
doing go
go
done
```

I believe the intention of Automat is that States are methods (rather than attributes like `attr.ib` would do it) only for:

* their names, which can then appear as nicely-accessible attributes of the hosting class, making all the `.upon()` statements easy to write
* a place to add arguments things like `(initial=True)`

and Inputs are methods only for:

* their names, as above
* their names, to be accessible from outside the class, so other "upstream" objects can invoke `target.inputXYZ(args)` to effect a state transition
* their method signatures, so they can be compared against Outputs

Outputs are allowed to have behavior, so they're fully justified in being real methods.

The bodies of States aren't executed, but apparently the bodies of Inputs are, when the input function is executed.

As Glyph pointed out, really Automat should use `dis` to inspect the bodies of both Inputs and States, and insist that they're empty at class-evaluation time. But a good starting point would be to ensure that the bodies aren't ever invoked, since that will help teach users about the intended emptiness.

**Comment by warner** [comment]
Take a look at that branch: it's a start, but it reveals another problem.

Currently it fails test_methodName, which incidentally exercised an additional property that we want: the call signature of the input method should be enforced, even if we don't want the input method itself to be executed. To fix this, we'll need MethodicalInput/doInput to extract the signature from the wrapped method, then compare the args/kwargs that it got against them, and raise an (identical?) TypeError if they don't match.

It may be easier to enforce empty method bodies, than to both avoid calling them *and* get call-signature checking.

**Comment by glyph** [comment]
Enforcing empty method bodies with `dis` was definitely what I was thinking for this, not avoiding the call entirely.  In fact, we want to call it so that the `coverage` module picks up that the callable is not un-covered, as well as to check the type signature :).

**Comment by warner** [comment]
Ok, that new branch looks at `co_code` to assert that it looks like `pass` or `return None`, with an optional docstring. It doesn't use `dis` (which is pretty hardwired to print to stdout), but the approach works on both py2 and py3. I don't know about pypy, I'll wait to see what travis says (I don't even know if `__code__` or `__code__.co_code` exists there.. we should probably do a `hasattr()` check first).
