### ISSUE TITLE
assert that transitions are unique

### ISSUE THREAD

**Issue by warner** [glyph/automat#51]
While working on adding tracing, I accidentally had a machine with transitions like this:

```python
    begin.upon(go1, middle, [out])
    middle.upon(go2, end, [out])
    end.upon(back, middle, [])
    end.upon(back, begin, [])
```

and then I was surprised when calling ``m.back`` from the ``end`` state gave me an error:

```
    raise NoTransition(state=inState, symbol=inputSymbol)
automat._core.NoTransition: no transition for MethodicalInput(method=<function go2 at 0x10365d1b8>) in MethodicalState(method=<function begin at 0x103653f50>)
```

Of course my machine should have used:

```python
    begin.upon(go1, middle, [out])
    middle.upon(go2, end, [out])
    end.upon(back, middle, [])
    middle.upon(back, begin, [])
```

I could have discovered this earlier if MethodicalMachine had complained to me that I was registering two transitions with the same state and the same input, instead of allowing the most recent ``.upon()`` call to silently win.

I think this might require the `Automaton._transitions` to record dicts of dicts instead of a flat list of tuples. Or maybe the `Automaton.addTransition` method could just search the existing list for partial matches and raise an exception if one is found.

Incidentally, is there much value in having that NoTransition exception's string form include all that "MethodicalInput" and object ID noise? I'd find it easier to read if it said:

```
    raise NoTransition(state=inState, symbol=inputSymbol)
automat._core.NoTransition: no transition from state=begin for input=go2
```

The actual state and input "symbol" objects are available on the exception object, should any exception handlers need them.

**Comment by glyph** [comment]
Yes, this would definitely be useful functionality!

Perhaps this is a case where the `__str__` should be a lot simpler than the `__repr__`.
