### ISSUE TITLE
Link to ClusterHQ article is broken

### ISSUE THREAD

**Issue by adiroiban** [glyph/automat#88]
And it is not archived :( 
https://web.archive.org/web/*/https://clusterhq.com/blog/what-is-a-state-machine/

Maybe just remove the link, or maybe @exarkun or someone else from ClusterHQ have a copy and can republish it

Thanks

**Comment by adiroiban** [comment]
And maybe in GitHub add the link to http://automat.readthedocs.io/en/latest/ as the site of this repo to make it easier to find the readthedocs page.

AFAIK the README does not talk about the read the docs site

**Comment by itamarst** [comment]
They're available on http://archive.li/, e.g. http://archive.is/oWpiI

**Comment by markrwilliams** [comment]
Only the first is available there: http://archive.is/clusterhq.com

Anybody happen to have a complete set?
