### ISSUE TITLE
inheritance - object oriented machines

### ISSUE THREAD

**Issue by bitfinity** [glyph/automat#89]
I've noticed problems while trying to develop machines using automat that inherit from base machine classes.
1. @output's defined in base methods misinterpret the fact that the super() is called in the following way:
`
File ".../automat/_methodical.py", line 274, in __get__method=self.method.__name__
AttributeError: GiveFeedback._initialize is a state-machine output method; to produce this output, call an input method instead.
`
2. It is not obvious how to define transitions using states and outputs defined in base classes. It appears that states are attached to the base class before instantiation as methodicStates but how do you reference them? Outputs seem to be instantiated upon object creation.

**Comment by glyph** [comment]
Hi @bitfinity! Thanks for using automat.

In my personal opinion, inheritance is a bad idea generally, and you should favor composition. This is *particularly* true in Automat, where composition allows for a combinatorially smaller state-space than derived machine structures.

That said, my personal feelings are somewhat secondary to how it might fit into the design. Either way there is an issue here: the documentation should explicitly call out that inheritance is not supported and the error message should make that clear (not effectively failing by accident, which is what it does now), OR if there’s a compelling use case we should figure out how this should work.

So: what is your use-case, specifically, for combining inheritance and automat?

Thanks again!

**Comment by bitfinity** [comment]
@glyph Hi Glyph, I think the rationale was there were a lot of actions that were in common between my state machines. I ended up using another library where the actions could be sent directly to another library, and hence, shared. I would have a "runner" or "responder" passed into the machine, and I would make the action be machine.responder.action. I think I remember that yours required a decorator within the machine, which meant that they had to be in the same class as the machine. So I would end up having to write a bunch of methods that just called the base level actions.
