### ISSUE TITLE
typos/errors in docs

### ISSUE THREAD

**Issue by ReblochonMasque** [glyph/automat#99]
on the [visualization page](https://automat.readthedocs.io/en/latest/visualize.html), should the `output_on_change_state` method be decorated with `@_machine.output()` i/o `@_machine.input()`?

If yes, I will propose a PR.  
I have not because the learning curve is quite steep, and I am not that familiar with state machines yet.

**Comment by ReblochonMasque** [comment]
Nobody home?

**Comment by glyph** [comment]
Yep, it should be an output, not an input.

**Comment by moshez** [comment]
This has been fixed for ~2 years, making closed/
